// ─── スタイル別 CSS トークン ───────────────────────────────────
// HTML レンダリング時に CSS 変数として注入する色・余白・字形定義

export const STYLE_TOKENS = {
  bootcamp: {
    bg: "#070D1C",
    fg: "#FFFFFF",
    muted: "rgba(255,255,255,0.58)",
    accent: "#FFB72B",
    secondary: "#18D4FF",
    rule: "rgba(255,255,255,0.14)",
    fontHead: "'Noto Sans JP', 'Hiragino Kaku Gothic ProN', 'Yu Gothic', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', 'Hiragino Kaku Gothic ProN', system-ui, sans-serif",
    fontNum: "'Inter', 'Helvetica Neue', system-ui, sans-serif",
    weightHead: 900,
  },
  bootcamp_light: {
    bg: "#FAFBFC",
    fg: "#0A2540",
    muted: "rgba(10,37,64,0.55)",
    accent: "#C4933A",
    secondary: "#635BFF",
    rule: "rgba(196,147,58,0.55)",
    fontHead: "'Noto Sans JP', 'Hiragino Kaku Gothic ProN', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', 'Hiragino Kaku Gothic ProN', system-ui, sans-serif",
    fontNum: "'Inter', 'Helvetica Neue', system-ui, sans-serif",
    weightHead: 900,
  },
  stripe: {
    bg: "#FFFFFF",
    fg: "#0A2540",
    muted: "#425466",
    accent: "#635BFF",
    secondary: "#00D4FF",
    rule: "#E3E8EE",
    fontHead: "'Noto Sans JP', 'Inter', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Inter', system-ui, sans-serif",
    weightHead: 800,
  },
  apple: {
    bg: "#FFFFFF",
    fg: "#1D1D1F",
    muted: "#86868B",
    accent: "#0071E3",
    secondary: "#86868B",
    rule: "#D2D2D7",
    fontHead: "'Noto Sans JP', 'SF Pro Display', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'SF Pro Display', 'Inter', system-ui, sans-serif",
    weightHead: 700,
  },
  anthropic: {
    bg: "#F8F4EE",
    fg: "#181818",
    muted: "rgba(24,24,24,0.55)",
    accent: "#CC785C",
    secondary: "#2D5A6F",
    rule: "rgba(204,120,92,0.45)",
    fontHead: "'Noto Serif JP', 'Tiempos', Georgia, serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Tiempos', 'Inter', system-ui, sans-serif",
    weightHead: 700,
  },
  linear: {
    bg: "#08090A",
    fg: "#F4F4F5",
    muted: "#A8A8B5",
    accent: "#5E6AD2",
    secondary: "#A8A8B5",
    rule: "rgba(168,168,181,0.25)",
    fontHead: "'Noto Sans JP', 'Inter', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Inter', monospace",
    weightHead: 700,
  },
  vercel: {
    bg: "#000000",
    fg: "#FFFFFF",
    muted: "#888888",
    accent: "#FF0080",
    secondary: "#7928CA",
    rule: "rgba(255,255,255,0.15)",
    fontHead: "'Noto Sans JP', 'Inter Display', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Inter', system-ui, sans-serif",
    weightHead: 800,
  },
  mckinsey: {
    bg: "#051C2C",
    fg: "#FFFFFF",
    muted: "rgba(255,255,255,0.55)",
    accent: "#B5985A",
    secondary: "#7FB7BD",
    rule: "rgba(181,152,90,0.6)",
    fontHead: "'Noto Serif JP', Georgia, serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "Georgia, 'Inter', serif",
    weightHead: 700,
  },
  notion: {
    bg: "#FFFFFF",
    fg: "#37352F",
    muted: "#787774",
    accent: "#2383E2",
    secondary: "#787774",
    rule: "#E9E9E7",
    fontHead: "'Noto Sans JP', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'JetBrains Mono', monospace",
    weightHead: 700,
  },
  google: {
    bg: "#FFFFFF",
    fg: "#202124",
    muted: "#5F6368",
    accent: "#4285F4",
    secondary: "#EA4335",
    rule: "#DADCE0",
    fontHead: "'Noto Sans JP', 'Google Sans', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Google Sans', 'Inter', system-ui, sans-serif",
    weightHead: 700,
  },
  figma: {
    bg: "#1E1E1E",
    fg: "#FFFFFF",
    muted: "#A0A0A0",
    accent: "#A259FF",
    secondary: "#1ABCFE",
    rule: "rgba(255,255,255,0.15)",
    fontHead: "'Noto Sans JP', 'Inter', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Inter', system-ui, sans-serif",
    weightHead: 800,
  },
  netflix: {
    bg: "#141414",
    fg: "#FFFFFF",
    muted: "#B3B3B3",
    accent: "#E50914",
    secondary: "#B3B3B3",
    rule: "rgba(255,255,255,0.15)",
    fontHead: "'Noto Sans JP', 'Bebas Neue', 'Inter', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Bebas Neue', 'Inter', system-ui, sans-serif",
    weightHead: 900,
  },
  kimetsu: {
    bg: "#07110D",
    fg: "#F7F1E5",
    muted: "rgba(247,241,229,0.62)",
    accent: "#C51F2C",
    secondary: "#1F7A5C",
    rule: "rgba(197,31,44,0.55)",
    fontHead: "'Noto Serif JP', 'Noto Sans JP', Georgia, serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Inter', 'Noto Sans JP', system-ui, sans-serif",
    weightHead: 800,
  },
  canva: {
    bg: "#FFFFFF",
    fg: "#0A0A0A",
    muted: "#666666",
    accent: "#00C4CC",
    secondary: "#7D2AE8",
    rule: "#E5E5E5",
    fontHead: "'Noto Sans JP', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Inter', system-ui, sans-serif",
    weightHead: 800,
  },
  nike: {
    bg: "#FFFFFF",
    fg: "#111111",
    muted: "#757575",
    accent: "#FA5400",
    secondary: "#111111",
    rule: "#111111",
    fontHead: "'Noto Sans JP', 'Helvetica Neue', system-ui, sans-serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Helvetica Neue', 'Inter', system-ui, sans-serif",
    weightHead: 900,
  },
  muji: {
    bg: "#F5F1EA",
    fg: "#2A2A2A",
    muted: "#888888",
    accent: "#A33B2A",
    secondary: "#888888",
    rule: "rgba(42,42,42,0.15)",
    fontHead: "'Noto Serif JP', Georgia, serif",
    fontBody: "'Noto Sans JP', system-ui, sans-serif",
    fontNum: "'Inter', system-ui, sans-serif",
    weightHead: 500,
  },
};

export function getTokens(styleName) {
  return STYLE_TOKENS[styleName] || STYLE_TOKENS.bootcamp;
}
